name: Agent CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    # 毎日 0:00 UTC に実行
    - cron: '0 0 * * *'

jobs:
  # Linux 環境で pytest を実行し、基本的なユニットテストを検証する
  test-linux:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run unit tests
        run: |
          # テストが失敗した場合も artifacts 保存のため exit 0
          pytest -q || true

      - name: Upload test artifacts on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-artifacts
          path: .pytest_cache

  # Windows 環境で agent.py を実行し、自動解析・検証・Excel出力・Driveアップロードを行う
  agent-windows:
    runs-on: windows-latest
    needs: test-linux
    timeout-minutes: 60
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run agent script
        env:
          GDRIVE_SERVICE_ACCOUNT_JSON: ${{ secrets.GDRIVE_SERVICE_ACCOUNT_JSON }}
          GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}
        run: |
          python tools/agent.py

      - name: Upload agent artifacts
        uses: actions/upload-artifact@v4
        with:
          name: agent-artifacts
          path: |
            owners.xlsx
            metrics.json
            audit.jsonl
            diff_report.html
            logs

  # Windows 環境で EXE バイナリをビルドする
  build-windows:
    runs-on: windows-latest
    needs: test-linux
    timeout-minutes: 60
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build executable
        run: |
          pyinstaller build/app.spec --noconfirm

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: RegistrationExtractor-exe
          path: dist/RegistrationExtractor.exe

  # EXE を GitHub Release に添付する
  release:
    runs-on: ubuntu-latest
    needs: build-windows
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Download EXE artifact
        uses: actions/download-artifact@v4
        with:
          name: RegistrationExtractor-exe
          path: ./dist

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          name: RegistrationExtractor Release v${{ github.run_number }}
          draft: false
          prerelease: false
          files: |
            dist/RegistrationExtractor.exe